import { createApiHandlers, type ApiDependencies } from "@bdta/application";
import {
  achievementCertificateHtmlSchema,
  achievementTypeCollectionSchema,
  achievementTypeDetailSchema,
  adminIntegrationCallbackLogCollectionSchema,
  adminIntegrationCallbackLogDetailSchema,
  blogPostCollectionSchema,
  blogPostDetailSchema,
  appointmentTypeCollectionSchema,
  appointmentTypeDetailSchema,
  adminJobLogCollectionSchema,
  adminJobLogDetailSchema,
  adminRouteAccessSchema,
  adminActorProfileSchema,
  adminWorkflowCollectionSchema,
  adminWorkflowDetailSchema,
  adminWorkflowEnrollmentCollectionSchema,
  adminWorkflowStepCollectionSchema,
  adminWorkflowStepEditorSchema,
  adminClientProfileDetailSchema,
  adminDashboardSchema,
  adminCrudActionSchema,
  authSessionSchema,
  bookingCalendarSyncResponseSchema,
  bookingIcalFeedSchema,
  bookingCollectionSchema,
  bookingDetailSchema,
  clientAchievementCollectionSchema,
  clientAchievementDetailSchema,
  clientCollectionSchema,
  clientContactCollectionSchema,
  clientContactDetailSchema,
  clientDetailSchema,
  contractCollectionSchema,
  contractDetailSchema,
  creditCollectionSchema,
  creditDetailSchema,
  deleteResponseSchema,
  emailTemplateCollectionSchema,
  emailTemplateDetailSchema,
  formSubmissionCollectionSchema,
  formSubmissionDetailSchema,
  integrationCallbackReceiptSchema,
  portalNotificationCollectionSchema,
  portalActorProfileSchema,
  portalSummarySchema,
  portalActionSchema,
  publicContactResponseSchema,
  publicBookingRequestSchema,
  invoiceCollectionSchema,
  invoiceDetailSchema,
  invoicePaymentSessionResponseSchema,
  portalProfileDetailSchema,
  packageCollectionSchema,
  packageDetailSchema,
  petCollectionSchema,
  petDetailSchema,
  petFileContentSchema,
  petFileCollectionSchema,
  petFileDetailSchema,
  quoteCollectionSchema,
  quoteDetailSchema,
  scheduledTaskCollectionSchema,
  scheduledTaskDetailSchema,
  settingCollectionSchema,
  settingDetailSchema,
  sitePageCollectionSchema,
  sitePageDetailSchema,
  successResponseSchema,
  workflowEnrollableClientCollectionSchema
} from "@bdta/contracts";
import { appSurfaces, providerCapabilities } from "@bdta/platform";

export const apiRuntimeManifest = {
  name: "bdta-api",
  surface: "api",
  supports: {
    auth: authSessionSchema,
    publicBooking: publicBookingRequestSchema,
    publicContact: publicContactResponseSchema,
    publicBlogPosts: blogPostCollectionSchema,
    publicBlogPostDetail: blogPostDetailSchema,
    publicSitePage: sitePageDetailSchema,
    publicQuoteDetail: quoteDetailSchema,
    publicContractDetail: contractDetailSchema,
    publicFormSubmissionDetail: formSubmissionDetailSchema,
    publicBookingIcalDetail: bookingIcalFeedSchema,
    portalActorProfile: portalActorProfileSchema,
    portalProfile: portalProfileDetailSchema,
    portalProfileUpdate: portalProfileDetailSchema,
    portalSummary: portalSummarySchema,
    portalAchievements: clientAchievementCollectionSchema,
    portalAchievementDetail: clientAchievementDetailSchema,
    portalAchievementCertificate: achievementCertificateHtmlSchema,
    portalBookings: bookingCollectionSchema,
    portalBookingDetail: bookingDetailSchema,
    portalContacts: clientContactCollectionSchema,
    portalContactDetail: clientContactDetailSchema,
    portalContactDelete: deleteResponseSchema,
    portalPets: petCollectionSchema,
    portalPetDetail: petDetailSchema,
    portalPetFiles: petFileCollectionSchema,
    portalPetFileUpload: petFileDetailSchema,
    portalPetFileDetail: petFileDetailSchema,
    portalPetFileContent: petFileContentSchema,
    portalPetFileDelete: deleteResponseSchema,
    portalInvoices: invoiceCollectionSchema,
    portalInvoiceDetail: invoiceDetailSchema,
    portalQuotes: quoteCollectionSchema,
    portalQuoteDetail: quoteDetailSchema,
    portalQuoteAccept: quoteDetailSchema,
    portalContracts: contractCollectionSchema,
    portalContractDetail: contractDetailSchema,
    portalContractSign: contractDetailSchema,
    portalForms: formSubmissionCollectionSchema,
    portalFormDetail: formSubmissionDetailSchema,
    portalFormSubmit: formSubmissionDetailSchema,
    portalNotifications: portalNotificationCollectionSchema,
    portalPackages: packageCollectionSchema,
    portalPackageDetail: packageDetailSchema,
    portalCredits: creditCollectionSchema,
    portalCreditDetail: creditDetailSchema,
    portalInvoicePaymentSession: invoicePaymentSessionResponseSchema,
    adminActorProfile: adminActorProfileSchema,
    adminRouteAccess: adminRouteAccessSchema,
    adminDashboard: adminDashboardSchema,
    adminBlogPosts: blogPostCollectionSchema,
    adminBlogPostDetail: blogPostDetailSchema,
    adminBlogPostCreate: blogPostDetailSchema,
    adminBlogPostUpdate: blogPostDetailSchema,
    adminSitePages: sitePageCollectionSchema,
    adminSitePageDetail: sitePageDetailSchema,
    adminSitePageCreate: sitePageDetailSchema,
    adminSitePageUpdate: sitePageDetailSchema,
    adminSettings: settingCollectionSchema,
    adminSettingDetail: settingDetailSchema,
    adminSettingUpdate: settingDetailSchema,
    adminAppointmentTypes: appointmentTypeCollectionSchema,
    adminAppointmentTypeDetail: appointmentTypeDetailSchema,
    adminEmailTemplates: emailTemplateCollectionSchema,
    adminEmailTemplateDetail: emailTemplateDetailSchema,
    adminScheduledTasks: scheduledTaskCollectionSchema,
    adminScheduledTaskDetail: scheduledTaskDetailSchema,
    adminAchievementTypes: achievementTypeCollectionSchema,
    adminAchievementTypeDetail: achievementTypeDetailSchema,
    adminJobLogs: adminJobLogCollectionSchema,
    adminJobLogDetail: adminJobLogDetailSchema,
    adminIntegrationCallbackLogs: adminIntegrationCallbackLogCollectionSchema,
    adminIntegrationCallbackLogDetail: adminIntegrationCallbackLogDetailSchema,
    adminClients: clientCollectionSchema,
    adminClientDetail: clientDetailSchema,
    adminClientProfile: adminClientProfileDetailSchema,
    adminClientCreate: adminClientProfileDetailSchema,
    adminClientUpdate: adminClientProfileDetailSchema,
    adminClientContacts: clientContactCollectionSchema,
    adminClientContactDetail: clientContactDetailSchema,
    adminClientContactDelete: deleteResponseSchema,
    adminClientAchievements: clientAchievementCollectionSchema,
    adminClientAchievementDetail: clientAchievementDetailSchema,
    adminClientAchievementCertificate: achievementCertificateHtmlSchema,
    adminPets: petCollectionSchema,
    adminPetDetail: petDetailSchema,
    adminPetFiles: petFileCollectionSchema,
    adminPetFileUpload: petFileDetailSchema,
    adminPetFileDetail: petFileDetailSchema,
    adminPetFileContent: petFileContentSchema,
    adminPetFileDelete: deleteResponseSchema,
    adminBookings: bookingCollectionSchema,
    adminBookingDetail: bookingDetailSchema,
    adminBookingCalendarSync: bookingCalendarSyncResponseSchema,
    adminBookingCalendarSyncDetail: bookingCalendarSyncResponseSchema,
    adminInvoices: invoiceCollectionSchema,
    adminInvoiceDetail: invoiceDetailSchema,
    adminQuotes: quoteCollectionSchema,
    adminQuoteDetail: quoteDetailSchema,
    adminContracts: contractCollectionSchema,
    adminContractDetail: contractDetailSchema,
    adminForms: formSubmissionCollectionSchema,
    adminFormDetail: formSubmissionDetailSchema,
    adminPackages: packageCollectionSchema,
    adminPackageDetail: packageDetailSchema,
    adminCredits: creditCollectionSchema,
    adminCreditDetail: creditDetailSchema,
    adminWorkflows: adminWorkflowCollectionSchema,
    adminWorkflowDetail: adminWorkflowDetailSchema,
    adminWorkflowCreate: adminWorkflowDetailSchema,
    adminWorkflowUpdate: adminWorkflowDetailSchema,
    adminWorkflowDelete: successResponseSchema,
    adminWorkflowEnrollments: adminWorkflowEnrollmentCollectionSchema,
    adminWorkflowEnrollableClients: workflowEnrollableClientCollectionSchema,
    adminWorkflowEnroll: successResponseSchema,
    adminWorkflowEnrollmentCancel: successResponseSchema,
    adminWorkflowSteps: adminWorkflowStepCollectionSchema,
    adminWorkflowStepEditor: adminWorkflowStepEditorSchema,
    adminWorkflowStepCreate: adminWorkflowStepEditorSchema,
    adminWorkflowStepUpdate: adminWorkflowStepEditorSchema,
    adminWorkflowStepDelete: successResponseSchema,
    portalActions: portalActionSchema,
    adminCrud: adminCrudActionSchema,
    callbacks: integrationCallbackReceiptSchema
  },
  appSurfaces,
  providerCapabilities
} as const;

export function listApiContracts(): string[] {
  return Object.keys(apiRuntimeManifest.supports);
}

export function buildApiRuntime(dependencies: ApiDependencies) {
  return {
    manifest: apiRuntimeManifest,
    handlers: createApiHandlers(dependencies)
  };
}
